#!/bin/sh

set -eu

if ! command -v afl-showmap > /dev/null; then
    echo >&2 "$0: afl-showmap not found!"
    echo >&2
    echo >&2 "You can get it from <http://lcamtuf.coredump.cx/afl/> as part of afl."
    exit 127
fi

AFL_SKIP_BIN_CHECK=1 exec afl-showmap "$@"
